topic: app
partitionKey: client
fields:
  client:
    type: mac
    min: 00:00:00:00:00:11
    max: 00:00:00:00:00:44
  application:
    type: collection
    values:
        - Skype
        - Facebook
        - Google
        - LinkedIn
        - Instagram
        - Twitter
        - Imgur
        - Mail
